In [22]:
import pandas as pd
from IPython.display import display

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 100)


df = pd.read_csv("Titanic_Survival_Dataset.csv")

print("========= FIRST 5 ROWS =========")
display(df.head())

print("\n========= LAST 5 ROWS =========")
display(df.tail())

print("\n========= SHAPE =========")
print(df.shape)

print("\n========= COLUMN NAMES =========")
print(df.columns.tolist())

print("\n========= DATA TYPES =========")
print(df.dtypes)

print("\n========= MISSING VALUES =========")
print(df.isnull().sum())

print("\n========= STATISTICAL SUMMARY =========")
display(df.describe())

print("\n========= SURVIVAL COUNT =========")
print(df["Survived"].value_counts())

print("\n========= GENDER COUNT =========")
print(df["Sex"].value_counts())

print("\n========= PASSENGER CLASS COUNT =========")
print(df["Pclass"].value_counts())

print("\n========= AVERAGE AGE =========")
print(df["Age"].mean())

print("\n========= HIGHEST FARE =========")
print(df["Fare"].max())

print("\n========= OLDEST PASSENGER =========")
display(df[df["Age"] == df["Age"].max()])

print("\n========= Youngest PASSENGER =========")
display(df[df["Age"] == df["Age"].min()])

print("\n========= FEMALE PASSENGERS =========")
display(df[df["Sex"] == "female"].head())

print("\n========= PASSENGERS WHO SURVIVED =========")
display(df[df["Survived"] == 1].head())

print("\n========= SORT BY FARE (DESCENDING) =========")
display(df.sort_values(by="Fare", ascending=False).head(10))

print("\n========= Survival Rate) =========")
survivalrate = df["Survived"].mean() * 100
print(f"Survival Rate: {survivalrate:.2f}%")

print("\n========= Survival Rate Acc. to Passenger Class =========")
print(df.groupby("Pclass")["Survived"].mean())

print("\n========= Average Fare Paid =========")
print(df["Fare"].mean())

print("\n========= Unique Pclass  =========")
print(df["Pclass"].nunique())

print("\n========= Unique Tickets Types  =========")
print(df["Ticket"].nunique())

print("\n========= Passenger Name Start with B  =========")

display(df[df["Name"].str.startswith("B")])

========= FIRST 5 ROWS =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

========= LAST 5 ROWS =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

========= SHAPE =========
(891, 12)

========= COLUMN NAMES =========
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

========= DATA TYPES =========
PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

========= MISSING VALUES =========
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

========= STATISTICAL SUMMARY =========

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

========= SURVIVAL COUNT =========
Survived
0    549
1    342
Name: count, dtype: int64

========= GENDER COUNT =========
Sex
male      577
female    314
Name: count, dtype: int64

========= PASSENGER CLASS COUNT =========
Pclass
3    491
1    216
2    184
Name: count, dtype: int64

========= AVERAGE AGE =========
29.69911764705882

========= HIGHEST FARE =========
512.3292

========= OLDEST PASSENGER =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0,A23,S

========= Youngest PASSENGER =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
803,804,1,3,"Thomas, Master. Assad Alexander",male,0.42,0,1,2625,8.5167,NaN,C

========= FEMALE PASSENGERS =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

========= PASSENGERS WHO SURVIVED =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

========= SORT BY FARE (DESCENDING) =========

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.0,3,2,19950,263.0000,C23 C25 C27,S
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
341,342,1,1,"Fortune, Miss. Alice Elizabeth",female,24.0,3,2,19950,263.0000,C23 C25 C27,S
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
742,743,1,1,"Ryerson, Miss. Susan Parker ""Suzette""",female,21.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
311,312,1,1,"Ryerson, Miss. Emily Borie",female,18.0,2,2,PC 17608,262.3750,B57 B59 B63 B66,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.0,0,1,PC 17558,247.5208,B58 B60,C

========= Survival Rate) =========
Survival Rate: 38.38%

========= Survival Rate Acc. to Passenger Class =========
Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

========= Average Fare Paid =========
32.204207968574636

========= Unique Pclass  =========
3

========= Unique Tickets Types  =========
681

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,26.5500,C103,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33.00,3,0,3101278,15.8500,NaN,S
112,113,0,3,"Barton, Mr. David John",male,22.00,0,0,324669,8.0500,NaN,S
118,119,0,1,"Baxter, Mr. Quigg Edmond",male,24.00,0,1,PC 17558,247.5208,B58 B60,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
143,144,0,3,"Burke, Mr. Jeremiah",male,19.00,0,0,365222,6.7500,NaN,Q
149,150,0,2,"Byles, Rev. Thomas Roussel Davids",male,42.00,0,0,244310,13.0000,NaN,S
150,151,0,2,"Bateman, Rev. Robert James",male,51.00,0,0,S.O.P. 1166,12.5250,NaN,S
162,163,0,3,"Bengtsson, Mr. John Viktor",male,26.00,0,0,347068,7.7750,NaN,S
168,169,0,1,"Baumann, Mr. John D",male,NaN,0,0,PC 17318,25.9250,NaN,S
183,184,1,2,"Becker, Master. Richard F",male,1.00,2,1,230136,39.0000,F4,S
188,189,0,3,"Bourke, Mr. John",male,40.00,1,1,364849,15.5000,NaN,Q
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.00,0,0,PC 17610,27.7208,B4,C
206,207,0,3,"Backstrom, Mr. Karl Alfred",male,32.00,1,0,3101278,15.8500,NaN,S
209,210,1,1,"Blank, Mr. Henry",male,40.00,0,0,112277,31.0000,A31,C
218,219,1,1,"Bazzani, Miss. Albina",female,32.00,0,0,11813,76.2917,D15,C
221,222,0,2,"Bracken, Mr. James H",male,27.00,0,0,220367,13.0000,NaN,S
225,226,0,3,"Berglund, Mr. Karl Ivar Sven",male,22.00,0,0,PP 4348,9.3500,NaN,S
248,249,1,1,"Beckwith, Mr. Richard Leonard",male,37.00,1,1,11751,52.5542,D35,S
269,270,1,1,"Bissette, Miss. Amelia",female,35.00,0,0,PC 17760,135.6333,C99,S
290,291,1,1,"Barber, Miss. Ellen ""Nellie""",female,26.00,0,0,19877,78.8500,NaN,S
291,292,1,1,"Bishop, Mrs. Dickinson H (Helen Walton)",female,19.00,1,0,11967,91.0792,B49,C
299,300,1,1,"Baxter, Mrs. James (Helene DeLaudeniere Chaput)",female,50.00,0,1,PC 17558,247.5208,B58 B60,C
327,328,1,2,"Ball, Mrs. (Ada E Hall)",female,36.00,0,0,28551,13.0000,D,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.00,0,0,16966,134.5000,E40,C
339,340,0,1,"Blackwell, Mr. Stephen Weart",male,45.00,0,0,113784,35.5000,T,S
345,346,1,2,"Brown, Miss. Amelia ""Mildred""",female,24.00,0,0,248733,13.0000,F33,S
356,357,1,1,"Bowerman, Miss. Elsie Edith",female,22.00,0,1,113505,55.0000,E33,S
362,363,0,3,"Barbara, Mrs. (Catherine David)",female,45.00,0,1,2691,14.4542,NaN,C
372,373,0,3,"Beavan, Mr. William Thomas",male,19.00,0,0,323951,8.0500,NaN,S
378,379,0,3,"Betros, Mr. Tannous",male,20.00,0,0,2648,4.0125,NaN,C
380,381,1,1,"Bidois, Miss. Rosalie",female,42.00,0,0,PC 17757,227.5250,NaN,C
387,388,1,2,"Buss, Miss. Kate",female,36.00,0,0,27849,13.0000,NaN,S
408,409,0,3,"Birkeland, Mr. Hans Martin Monsen",male,21.00,0,0,312992,7.7750,NaN,S
430,431,1,1,"Bjornstrom-Steffansson, Mr. Mauritz Hakan",male,28.00,0,0,110564,26.5500,C52,S
448,449,1,3,"Baclini, Miss. Marie Catherine",female,5.00,2,1,2666,19.2583,NaN,C
469,470,1,3,"Baclini, Miss. Helene Barbara",female,0.75,2,1,2666,19.2583,NaN,C
477,478,0,3,"Braund, Mr. Lewis Richard",male,29.00,1,0,3460,7.0458,NaN,S
484,485,1,1,"Bishop, Mr. Dickinson H",male,25.00,1,0,11967,91.0792,B49,C
507,508,1,1,"Bradley, Mr. George (""George Arthur Brayton"")",male,NaN,0,0,111427,26.5500,NaN,S
536,537,0,1,"Butt, Major. Archibald Willingham",male,45.00,0,0,113050,26.5500,B38,S
543,544,1,2,"Beane, Mr. Edward",male,32.00,1,0,2908,26.0000,NaN,S
546,547,1,2,"Beane, Mrs. Edward (Ethel Clarke)",female,19.00,1,0,2908,26.0000,NaN,S
593,594,0,3,"Bourke, Miss. Mary",female,NaN,0,2,364848,7.7500,NaN,Q
598,599,0,3,"Boulos, Mr. Hanna",male,NaN,0,0,2664,7.2250,NaN,C
614,615,0,3,"Brocklebank, Mr. William Alfred",male,35.00,0,0,364512,8.0500,NaN,S
618,619,1,2,"Becker, Miss. Marion Louise",female,4.00,2,1,230136,39.0000,F4,S
624,625,0,3,"Bowen, Mr. David John ""Dai""",male,21.00,0,0,54636,16.1000,NaN,S
628,629,0,3,"Bostandyeff, Mr. Guentcho",male,26.00,0,0,349224,7.8958,NaN,S
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.00,0,0,27042,30.0000,A23,S
644,645,1,3,"Baclini, Miss. Eugenie",female,0.75,2,1,2666,19.2583,NaN,C
657,658,0,3,"Bourke, Mrs. John (Catherine)",female,32.00,1,1,364849,15.5000,NaN,Q
661,662,0,3,"Badt, Mr. Mohamed",male,40.00,0,0,2623,7.2250,NaN,C
666,667,0,2,"Butler, Mr. Reginald Fenton",male,25.00,0,0,234686,13.0000,NaN,S
670,671,1,2,"Brown, Mrs. Thomas William Solomon (Elizabeth Catherine Ford)",female,40.00,1,1,29750,39.0000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.00,1,1,29750,39.0000,NaN,S
702,703,0,3,"Barbara, Miss. Saiide",female,18.00,0,1,2691,14.4542,NaN,C
728,729,0,2,"Bryhl, Mr. Kurt Arnold Gottfrid",male,25.00,1,0,236853,26.0000,NaN,S
733,734,0,2,"Berriman, Mr. William John",male,23.00,0,0,28425,13.0000,NaN,S
757,758,0,2,"Bailey, Mr. Percy Andrew",male,18.00,0,0,29108,11.5000,NaN,S
762,763,1,3,"Barah, Mr. Hanna Assi",male,20.00,0,0,2663,7.2292,NaN,C
766,767,0,1,"Brewe, Dr. Arthur Jackson",male,NaN,0,0,112379,39.6000,NaN,C
852,853,0,3,"Boulos, Miss. Nourelain",female,9.00,1,1,2678,15.2458,NaN,C
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.00,0,3,2666,19.2583,NaN,C
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.00,0,0,236852,13.0000,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.00,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.00,1,1,11751,52.5542,D35,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.00,0,0,C.A./SOTON 34068,10.5000,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.00,0,0,111369,30.0000,C148,C